### ISSUE TITLE
problem with publishing

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/remark-loader#25]
/cc @skipjack friendly ping, hi, we are ready for new major release with a lot of improvements, but unfortunately I don't have npm permissions, can you give me them https://www.npmjs.com/package/remark-loader?

**Comment by skipjack** [comment]
Hmmm, I thought I already sent you an invite while we were discussing #6. Anyway, just sent another 👍

**Comment by evilebottnawi** [comment]
@skipjack What is nickname you use? No invite on email :disappointed:

**Comment by evilebottnawi** [comment]
My bad, all is fine, thanks!
