### ISSUE TITLE
Upgrade remark to 13

### ISSUE THREAD

**Issue by chenxsan** [webpack-contrib/remark-loader#30]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- remark-loader Version:

### Feature Proposal

Remark 13 was out last month https://github.com/remarkjs/remark/releases/tag/13.0.0, and it brought a lot of changes, any plan to support it soon?

**Comment by evilebottnawi** [comment]
Yep, let's do it today

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/remark-loader/pull/31, WIP on release, notes:
- `remark` in `peerDeps`, so you should install `remark` itself and you can use `remark@12`/`remark@13`, I think it will be work with `remark@11` too
